image: itxtech/docker-env-genisys

stages:
 - package

phar:
  stage: package
  script:
   - mkdir plugins
   - sed -i "s/const VERSION \?= \?\"\(.*\)\"/const VERSION = \"\1-${CI_BUILD_REF:0:7}\"/" src/pocketmine/PocketMine.php
   - php tests/Travis.php
   - mv plugins/Genisys/Genisys*.phar .
  artifacts:
    paths:
     - Genisys*.phar

