always_rejected: 
  explanation: "This PR is still work in progress"
  labels: 
    - wip
  title_regex: (WIP|wip)
approve_by_comment: true
approve_regex: "(?<!(N|n|o|')t )((W|w)ork|(G|g)ood)|(A|a)pproved|\\+1"
author_approval: ignored
reject_regex: "(N|n|o|')t (W|w)|(R|r)ejected|-1"
reject_value: -1
reset_on_push: true
reviewers: 
  name: default
  required: 2
  teams: 
    - trusted
